apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-rules-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance-rules-playground
  template:
    metadata:
      labels:
        app: governance-rules-playground
    spec:
      containers:
        - name: governance-rules-playground
          image: 005904641462.dkr.ecr.us-east-2.amazonaws.com/governance-rules-playground:latest
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 3001
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: governance-rules-playground-prod-openai-user
                key: apikey